image: minfos/tesla-ci:stable

pipelines:
  branches:
    master:
      - step:
          script:
          - source build/ci/init.sh
          - source build/ci/release.sh
    release/*:
      - step:
          script:
          - source build/ci/init.sh
          - source build/ci/release.sh
          - source build/ci/publish.sh
  default:
    - step:
        script:
          - source build/ci/init.sh
          - source build/ci/work-in-progress.sh
  custom:
    "Pre-check a merge into the master branch":
      - step:
          script:
            - source build/ci/merge-check.sh
            - source build/ci/init.sh
            - source build/ci/release.sh
